### ISSUE TITLE
Reunião Inaugural

### ISSUE THREAD

**Issue by caeslucio** [fga-eps-mds/2022-2-Squad05#1]
## Descrição:
~~Dia 27/10, as 18:30, está marcada a reunião inaugural do nosso grupo na disciplina.~~
Dia 28/10, as 12:00, aconteceu a reunião inaugural do nosso grupo na disciplina.

### Atividades a serem realizadas pelos integrantes antes da reunião:
- Observar algum trabalho anterior realizado que está no repositório e trazer para o grupo suas impressões.
- Trazer idéias de temas que estariam de acordo com a proposta do semestre.

## Ata da Reunião:
Será colocada aqui durante a reunião.

**Comment by caeslucio** [comment]
Não conseguir atribuir as pessoas na Issue, então vou marcar os @ aqui:
@larigs
@knz13
@brunna-martins
@arthur-augusto
@analeticiaa

**Comment by analeticiaa** [comment]
**Toró de ideias**

Fizemos nossa primeira reunião para discutir os problemas encontrados na FGA e possíveis soluções para eles. Um resumão geral pode ser visto no [quadro do Miro](https://miro.com/welcomeonboard/eXVHSm5DWmcwMlY3ZTFSaHRrNVpDeTh2SmFraXhhajZNeUpnWWFiZXJlM3AzRFViR3A1YXMybGxmcmJOaVlITHwzNDU4NzY0NTE5NTQ0MjUxOTgwfDI=?share_link_id=599644518360).

![image](https://user-images.githubusercontent.com/56135971/198690853-5c9e116f-976d-4e5a-bd7f-b3e8b50dca26.png)

**Comment by caeslucio** [comment]
@larigs e @knz13, aceitem o convite na organização pra gente já começar a colocar mais informações aqui na Squad

**Comment by caeslucio** [comment]
Vou enviar aqui algumas prints com zoom maior nos temas trabalhados (mesmo que depois da mudança do plano de ensino talvez a gente tenha que mudar tudo, mas só pra deixar bonitinho por enquanto)

![Screenshot_20221028-132004_Miro.jpg](https://user-images.githubusercontent.com/22137470/199279016-0118b185-56eb-452f-b0fc-49d61e5ddda4.jpg)

![Screenshot_20221028-132024_Miro.jpg](https://user-images.githubusercontent.com/22137470/199279057-f3c5ce8f-57c0-4cdf-be41-a713cd4971ca.jpg)

![Screenshot_20221028-132033_Miro.jpg](https://user-images.githubusercontent.com/22137470/199279096-bacc84e8-59b1-4812-a2ed-cb80f86a08b8.jpg)

![Screenshot_20221028-132043_Miro.jpg](https://user-images.githubusercontent.com/22137470/199279180-4076857c-7c54-4589-a55d-b215b2f3f17c.jpg)

![Screenshot_20221028-132116_Miro.jpg](https://user-images.githubusercontent.com/22137470/199279240-762d223b-9ebf-4655-939a-f4a44512d870.jpg)
