### ISSUE TITLE
Épicos

### ISSUE THREAD

**Issue by knz13** [fga-eps-mds/2022-2-Squad05#20]
# Descrição

Precisamos definir os épicos que vamos fazer no projeto e que é o mais necessário

# Tarefas

* Escrever nessa issue o que cada um acha o mais importante para se ter no projeto
* Descrever a sua ideia o máximo possível

**Comment by knz13** [comment]
## Criação de um segundo bot

### Descrição

O bot principal seria responsável por receber os dados dos cursos, criar os cursos e editá-los. O segundo bot seria responsável por mandar cada curso que o "aluno" estaria inscrito e poder acompanhar o progresso junto ao "aluno"

### Features

* "aluno" ser capaz de acompanhar cada um dos cursos que ele está inscrito
* "aluno" ser capaz de visualizar a aula em que ele se encontra no curso
* "aluno" ser capaz de ver a porcentagem do curso já vista

## Registro de cada pessoa que utiliza o bot no banco de dados

### Descrição

Acredito que seja muito importante o registro de cada usuário quando ele inicia uma conversa com o bot, com a possibilidade de qualquer pessoa utilizar o bot e conseguir mandar o seu "curso"

### Features

* Verificar quando há o início de uma nova conversa, se a pessoa já foi cadastrada no banco de dados

## Mandar arquivo excel para o bot com links, comentários para cada link e os usuários que devem receber o curso

### Features

* Receber o arquivo, lê-lo e cadastrar no banco de dados os links, comentários associados, os usuários e o id da pessoa que criou o curso em uma collection chamada cursos.

**Comment by brunna-martins** [comment]
## Bot para criação e administração de um curso
### Descrição
Esse bot é o mais importante e será o que possibilita a criação de cursos, administração do conteúdo e monitoramento dos alunos inscritos.
O bot deve automatizar todo o processo de "entrega" de conteúdos. Dados os materiais disponibilizados pelo criador do curso, o bot deve enviar os materiais na ordem estabelecida pelo administrador. Um material só pode ser enviado quando o usuário "dizer" ao bot que já visualizou o material anterior. Assim, fica mais simples o acompanhamento do progresso dos alunos e, também, ficam mais organizados os estudos e tarefas de cada usuário.
### Features 
* Criação de curso: com nome, descrição, público-alvo, escola/empresa relacionada ao curso(se for o caso).
* Adição, edição e remoção de conteúdos: o criador do curso deve ser capaz de adicionar, editar e remover links para conteúdos, sejam eles pdfs, vídeos, websites, etc. Seria ideal que o usuário não tivesse que fazer download de nenhum desses conteúdos.
* Acompanhamento dos alunos: planilha contendo quantos e quais são os usuários inscritos no curso; e, se possível, em que ponto estão no curso.

## Bot para ser aluno do curso
### Descrição
Esse bot também é importante para que os usuários possam se inscrever no curso e possibilitar o acompanhamento de seu progresso por parte do criador do curso.
### Features 
* Receber conteúdos: a ideia central do bot é possibilitar o acesso aos materiais disponibilizados pelo criador do curso de forma sequencial e ordenada. Cada progresso do aluno deve ser computado e enviado para o administrador acompanhar o progresso do aluno.
* Voltar em conteúdos anteriores: não é o mais importante nesse bot, mas seria interessante que o aluno possa visitar materiais já passados caso queira.
