### ISSUE TITLE
Decidir flow da conversa com o bot de criação dos cursos

### ISSUE THREAD

**Issue by knz13** [fga-eps-mds/2022-2-Squad05#24]
# Descrição

Para podermos começar o desenvolvimento do bot, precisamos decidir como a conversa com o bot deverá proceder

# Necessidades

* Decidir as perguntas e respostas que o bot dará
* Decidir se haverá botões e quais os textos
* Documentar as implementações

**Comment by brunna-martins** [comment]
# Ideias
Previamente à discussão de nossas necessidades, deixarei aqui algumas ideias breves do que pode ser interessante à implementação do bot.

# Necessidades
## Bot Professor
Primeiramente, é necessário logar o professor. Seria interessante que seu login coincidisse com sua própria conta do Telegram (é possível)? Depois de logado, é necessário verificar se esse "professor" já possui cursos cadastrados e, caso não tenha, já direcioná-lo para a criação do curso. 
### Criação do Curso
São necessários:
* Nome do curso;
* Id do curso (importantíssimo, pois por meio do compartilhamento desse código, será possível aos alunos encontrar o curso!);
* Senha do curso (caso usemos o Id como forma de cadastrar um aluno ao curso, devemos pensar sobre a necessidade de uma chave de acesso.);
* Descrição do curso: esse curso é sobre o quê? Qual seu público-alvo? Há estimativa de tempo de conclusão?

### Acompanhamento e edição de cursos pré-existentes
Após sua criação, o professor deve ser capaz de administrar com facilidade o curso que criou.
* Compartilhamento de materiais: a parte crucial do projeto, que é o envio de conteúdos de forma sequencial e ordenada ao aluno. Nessa parte, deve ser possível ao professor que faça upload de arquivos, compartilhamento de links, escrita de texto de autoria própria (caso queira) para orientações, entre outros a serem discutidos. Além disso, o professor deve ser capaz de escolher a ordem em que os materiais serão enviados e quais materiais serão enviados a cada mensagem de texto (é necessário discutir se o professor pode alterar a ordem de materiais já enviados, pois isso impacta no progresso de alunos que já avançaram no curso; ou se a adição de novos materiais será adicionada ao final da "fila" de envio de recursos).
* Geração de planilha Excel para controle de quem está cadastrado no curso e acompanhamento do progresso dos alunos (a ser discutido).
* Exclusão do curso (e, certamente, é necessário descadastrar alunos participantes, retirando seu acesso aos materiais).

## Bot Aluno
Assim como o professor, é necessário seja logado em sua conta do tipo aluno. O mesmo se aplica em relação ao login poder coincidir com sua conta do Telegram, caso seja possível. 
### Visualização dos cursos
Assim que o aluno se conectar, deve ser capaz de visualizar os cursos em que está inscrito e, caso não esteja inscrito em nenhum curso, deve ser capaz de buscar um curso pelo seu id e se inscrever nele caso queira.
* É interessante que tenhamos botões para cada curso: o aluno escolhe qual curso deseja visualizar no momento, a fim de não misturar os conteúdos caso esteja cadastrado em mais de um curso.
### Inscrição em um curso
* O aluno deve ser capaz de buscar um curso a partir de seu id (precisamos discutir questões como chave de acesso).
### Acompanhamento do Curso
* Ao clicar no curso, o aluno deve receber o último conteúdo na fila de acordo com seu progresso.
* Um botão seria interessante para que o aluno confirmasse que já viu esse conteúdo, assim, o bot enviaria o próximo de acordo com a ordem definida pelo professor.
* Precisamos discutir a possibilidade de o aluno ver conteúdos anteriores, caso precise deles novamente (um botão de voltar, talvez?).
### Sair de um Curso
* Autoexplicativo. O aluno deve ser retirado da planilha do professor e parar de receber conteúdos, bem como não ser mais capaz de visualizar conteúdos já vistos ao longo de sua participação.

**Comment by knz13** [comment]
Gostei muito de todas as ideias, vou deixar aqui o que pensei sobre cada um dos tópicos

## Bot Professor 

### Login do Professor

* Acredito que o login do professor e dos alunos pode ser automático, já que as contas do telegram possuem ids automáticos que são únicos, assim qualquer pessoa poderia utilizar o serviço.

* Gostei bastante da ideia de caso ele não possua nenhum curso, já direciona-lo para o cadastro.

### Criação do Curso

* O id do curso acho q pode ser automáticamente criado e revelado após a criação do curso na página inicial do curso

* Senha do curso: Acredito que possa ser opcional caso tenha algum curso que seja interessante ser público

* Concordo com a necessidade da existencia da descrição

### Acompanhamento e Edição dos Cursos

* Acho que seria interessante que, quando o professor clicasse em editar um curso ele tivesse as opções de:

    * Editar Aula Específica

    * Alterar Ordem das Aulas

    * Ver Alunos

    * Remover Curso

* Quando clicasse em "Editar aula específica", ele pudesse ver todas as aulas atualmente cadastradas com o número da aula na frente do nome e ordenadas.
    * Ao clicar em uma delas ele teria as opções

        * Editar descrição

        * Editar materiais complementares

        * Ver progresso

        * Remover

        * Voltar
    
* Quando clicasse em alterar a ordem das aulas, ele visualizaria a lista com todas as aulas na ordem atual e receberia a instrução: "clique sequencialmente nas aulas conforme a ordem desejada", que ele poderia seguir caso desejasse. Haveria também um botão de voltar ao final

* Quando clicasse em ver alunos,
ele veria uma lista com todos os alunos e uma instrução: "Clique no nome do aluno que deseja saber mais..."
    * Ao clicar no nome aluno, ele veria algo como o que está abaixo
    
        - NOME DO ALUNO
        - PORCENTAGEM COMPLETA DO CURSO
    * E teria as opções (em botões)
        
        * Gerar Planilha de Aproveitamento

        * Remover Aluno

## Bot Aluno

* Acredito que é bom que esse seja um bot separado, para que as pessoas possam utilizar dos dois serviços simultaneamente caso desejem. Como a issue para a criação do bot dos alunos está na #25, acho que podemos deixar para eles resolverem. Se possível, pode mandar essa mesma mensagem lá
