### ISSUE TITLE
Decidir o flow da conversa com o bot dos alunos

### ISSUE THREAD

**Issue by knz13** [fga-eps-mds/2022-2-Squad05#25]
# Descrição

Os alunos também precisam ter uma conversa interessante e intuitiva para acessar os conteúdos dos cursos

# Necessidades

* Decidir as perguntas possíveis de serem feitas ao bot e as respostas que o bot poderá dar a cada uma
* Decidir se haverá a necessidade de botões em alguns locais e aonde
* Decidir as implementações e interações com o backend

**Comment by pxarthur** [comment]
# Bot Aluno

O bot que interage com o aluno deve conseguir disponibilizar o material fonecido pelo criador do curso, no momento e da forma que o professor desejar.

## Ideias

- Disponibilizar aulas de acordo com o cronograma
- Marcar aulas / exercícios como concluido

## Informações gerais

- Progresso: É medido conforme o aluno marca exercicos, aulas, questionarios como concluido
- Material disponível
- Aulas
    - Materiais de Aula
    - Disponíveis
    - Restritas
- Exercícios

## Materiais

### Material não específico
- Plano de Ensino
- Cronograma de Aulas
- Livro texto / Referências
- Exercícios / questionário

### Material especifico de uma aula
- Slide
- Texto
- Vídeo
