### ISSUE TITLE
Criar ambiente virtual python para o projeto

### ISSUE THREAD

**Issue by pxarthur** [fga-eps-mds/2022-2-Squad05#26]
# Descrição
Criar um ambiente virtual python ajuda na hora de testar o código, além de garatir que o projeto irá rodar uma determinada versão do python e dos pacotes python da API do telegram.

**Comment by brunna-martins** [comment]
[Tutorial Python](https://docs.python.org/pt-br/3/tutorial/venv.html).

Que versão do Python usaremos para esse projeto?

**Comment by pxarthur** [comment]
> [Tutorial Python](https://docs.python.org/pt-br/3/tutorial/venv.html).
> 
> Que versão do Python usaremos para esse projeto?

A não ser que tenha algum problema de compatibilidade a mais recente (3.10) deve ser a versão mais popular que ainda continua sendo atual.

**Comment by knz13** [comment]
Acredito que seja uma má ideia criar o ambiente virtual e coloca-lo no nosso repositório. Como está escrito [nessa pergunta](https://stackoverflow.com/questions/6590688/is-it-bad-to-have-my-virtualenv-directory-inside-my-git-repository) no StackOverflow, talvez seja interessante apenas criarmos um arquivo requirements.txt com os módulos e as versões necessárias e colocarmos no README uma descrição de como instalar os módulos:

```
    pip install -r requirements.txt
```

Para criarmos o arquivo, é preciso apenas executar o comando `pip freeze > requirements.txt` na linha de comando

**Comment by pxarthur** [comment]
> Acredito que seja uma má ideia criar o ambiente virtual e coloca-lo no nosso repositório. Como está escrito [nessa pergunta](https://stackoverflow.com/questions/6590688/is-it-bad-to-have-my-virtualenv-directory-inside-my-git-repository) no StackOverflow, talvez seja interessante apenas criarmos um arquivo requirements.txt com os módulos e as versões necessárias e colocarmos no README uma descrição de como instalar os módulos:
> 
> ```
>     pip install -r requirements.txt
> ```
> 
> Para criarmos o arquivo, é preciso apenas executar o comando `pip freeze > requirements.txt` na linha de comando

Entendi porque criar um ambiente virtual para o projeto não iria funcionar. Vou criar uma nova issue para adicionar o arquivo requirements.txt do projeto

**Comment by pxarthur** [comment]
A issue de criação do arquivo requirements.txt está em #27
