### ISSUE TITLE
Testes Unitários

### ISSUE THREAD

**Issue by analeticiaa** [fga-eps-mds/2022-2-Squad05#42]
**Precisamos realizar os testes unitários**

1. Pesquisar qual a melhor ferramenta para realizar os testes e como utilizar
2. Mapear as funções e métodos do projeto
3. Implementar os testes

**Comment by analeticiaa** [comment]
Como o projeto está sendo realizado em Python, podemos utilizar o Pytest.

Vantagens: 
- Permite execução de testes em paralelo; 
- Como é muito utilizado e conhecido, existe bastante conteúdo sobre o Pytest na internet;
- Facilidade na troca da execução de um teste, um conjunto ou uma suíte completa; 
- Detecta testes automaticamente baseando-se nos nomes dos arquivos e diretórios criados; 
- Open source

[Documentação do Pytest](https://docs.pytest.org/en/7.1.x/getting-started.html)

**Comment by knz13** [comment]
Eu dei merge com alguns exemplos de utilização do pytest pra nosso caso em #43
