### ISSUE TITLE
Como colocar um bot para funcionar: Arthur @arthur-augusto e Otavio @knz13

### ISSUE THREAD

**Issue by caeslucio** [fga-eps-mds/2022-2-Squad05#5]
# Descrição
>**Frente de estudo:**
>Como colocar um bot para funcionar: requisitos de linguagem e recursos de servidor necessários. Como criar o bot e mantê-lo online.

Estudar sobre as tecnologias de bot do telegram e quais a infraestrutura necessária para botar o bot para funcionar, tanto de servidor quanto para configuração no Telegram. 

# Tarefas
A ser discutido com os atribuídos.

# Critérios de aceitação
A ser definido.

**Comment by caeslucio** [comment]
Diversas tecnologias foram conversadas no grupo do WhatsApp e não repassadas para o Github porque o Scrum master não havia aberto a issue necessária para o compartilhamento das ideias.

**Comment by knz13** [comment]
Depois de estudar sobre a api do telegram e as documentações sobre o assunto, encontrei que é necessário fazermos os seguintes passos:
* criar o bot à partir do chat com o [BotFather](https://telegram.me/BotFather) do telegram
* criar um script em python (nossa linguagem escolhida) para responder às ações dos usuários (professor e alunos) com [essa](https://github.com/python-telegram-bot/python-telegram-bot) biblioteca
* hospedar o script em algum servidor ([firebase](https://firebase.google.com) ou [heroku](http://heroku.com) por exemplo) para poder responder às chamadas pela api do telegram em todos os momentos
* caso precisemos de um banco de dados para guardar as informações dos cursos, podemos utilizar o [Firestore](https://firebase.google.com/docs/firestore/quotas) do firebase (tier grátis com até 1gb de capacidade) por exemplo ou, caso precisemos cortar gastos no começo do projeto, podemos utilizar o Google Drive (15gb de capacidade grátis) e a sua [api](https://developers.google.com/drive) que já possui um wrapper para python
