### ISSUE TITLE
Exemplos de curso via chat: Larissa e Brunna

### ISSUE THREAD

**Issue by caeslucio** [fga-eps-mds/2022-2-Squad05#8]
# Descrição
>**Frente de estudo:**
>Exemplos de curso via chat: encontrar exemplos de bots que já fazem algo que procuramos desenvolver ou que faz algo parecido e que serviria de base para nosso modelo. Encontrar imagens ou fazer prints de casos de uso que forem encontrados.

Fazer o levantamento de épicos/features para o projeto. Pesquisar sobre cursos que utilizam a plataforma do telegram ou whatsapp para formação de alunos, e ver a estrutura de mensagens utilizada para o andamento do curso.

# Tarefas
- [x] Ter contato com um curso ou experiência relacionada
- [x] Relatar ao grupo a experiência de usuário
- [x] Disponibilizar prints da utilização ou mostrar o andamento do curso por outros meios

# Critérios de aceitação
- Acho que está bem definido nas tarefas, qualquer coisa poderá ser conversado em grupo posteriormente.

**Comment by larigs** [comment]
Forma de cadastro do usuário foi feito por meio de um redirecionamente para o site da organização responsável pelo curso.
![cursoSebrae](https://user-images.githubusercontent.com/97994511/204058691-e773371a-f22f-402b-933a-be72ef6a04d7.jpeg)

**Comment by larigs** [comment]
Para apresentação das opções de funções que o usuário pode escolher, foi utilizado uma caixa de seleção. Tendo em vista as funcionalidades pensadas para o projeto, essa opção pode ser utilizada para a escolha de qual turma o aluno deseja acessar, ou qual módulo de conteúdo.
![cursoSebrae2](https://user-images.githubusercontent.com/97994511/204058749-115f5432-3595-4bb1-9fc1-106f04132f2d.jpeg)
![cursoSebrae5](https://user-images.githubusercontent.com/97994511/204058783-4cad96c6-2b10-4954-b715-9001e690fe7a.jpeg)

**Comment by larigs** [comment]
O bot mostra outra forma de seleção de opções, ela foi considerada interessante pois seria uma forma interessante de aplicar a opção de CRUD, onde o professor poderia cadastrar/visualizar/deletar algum conteúdo ou perfil de determinado aluno, também pode ser pensada outras aplicações para essa funcionalidade.
![cursoSebrae3](https://user-images.githubusercontent.com/97994511/204059194-4caca2cc-97ea-4651-b5a1-531205e41c16.jpeg)

**Comment by larigs** [comment]
Como forma de apresentar ao usuário as opções de conteúdos em um módulo, devido ser algo que frequentemente é atualizado, o bot utilizou de uma listagem e a escolha sendo por meio do envio do número da opção escolhida, podendo ser aplicado de forma semelhante no projeto.
![cursoSebrae4](https://user-images.githubusercontent.com/97994511/204059397-e728383e-6619-4afc-ba14-8e96b5d6ac89.jpeg)
